modLoader="kotlinforforge"
loaderVersion="[3,)"
license="${mod_license}"
#issueTrackerURL="https://example.void/"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://example.void/updates.json" # See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#displayURL="https://example.void/"
#logoFile="vaultfixes.png"
#credits=""
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}" #mandatory
   ordering="NONE"
   side="SERVER"
[[dependencies.${mod_id}]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="SERVER"

# kotlin
[[dependencies.${mod_id}]]
   modId="kotlinforforge"
   mandatory=true
   versionRange="[3,)"
   ordering="AFTER"
   side="SERVER"

# libs
[[dependencies.${mod_id}]]
   modId="the_vault"
   mandatory=true
   versionRange="${the_vault_version}"
   ordering="AFTER"
   side="SERVER"
[[dependencies.${mod_id}]]
   modId="vaultintegrations"
   mandatory=true
   versionRange="${vaultintegrations_version}"
   ordering="AFTER"
   side="SERVER"
[[dependencies.${mod_id}]]
   modId="ispawner"
   mandatory=true
   versionRange="${ispawners_version}"
   ordering="AFTER"
   side="SERVER"
[[dependencies.${mod_id}]]
   modId="modularrouters"
   mandatory=true
   versionRange="${modular_routers_version}"
   ordering="AFTER"
   side="SERVER"
[[dependencies.${mod_id}]]
   modId="flan"
   mandatory=false
   versionRange="${flan_version}"
   ordering="AFTER"
   side="SERVER"
[[dependencies.${mod_id}]]
   modId="easy_villagers"
   mandatory=true
   versionRange="${easy_villagers_version}"
   ordering="AFTER"
   side="SERVER"
[[dependencies.${mod_id}]]
   modId="create"
   mandatory=true
   versionRange="${create_version}"
   ordering="AFTER"
   side="SERVER"
[[dependencies.${mod_id}]]
   modId="camera"
   mandatory=true
   versionRange="${camera_version}"
   ordering="AFTER"
   side="SERVER"